Repository wowba/Calit, pull requests merged in 2023-11, with the labels that each got.

#109 [#108] fix : ProjectModalLayout 탭 호버 색상 수정 및 themeProvider 속성 추가, 사용하지 않는 폰트 제거
  src/components/layout/ProjectModalLayout.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: fix, design

#111 [#104] feat & design : Project List 페이지 textarea 기능 업데이트 / 공통레이아웃으로 수정 / 스크롤바 디자인
  src/assets/icons/settingIconBlack.svg
  src/components/layout/CommonTextArea.tsx
  src/pages/ProjectListPage/ProjectCard.tsx
  src/pages/ProjectPage/TodoModal/MarkdownEditor.tsx
  src/pages/ProjectPage/TodoModal/UpdateContent.tsx
Labels: feat, design

#112 [#110] feat : 달력 내 칸반 호버시 수정 아이콘 팝업 및 기능 추가
  package-lock.json
  package.json
  public/index.html
  src/assets/icons/paint.svg
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
Labels: feat, design

#115 [#113] feat : 칸반 생성시 기본 스테이지 추가
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
Labels: feat

#117 [#116] feat : 에러페이지 컴포넌트 추가
  src/components/ErrorPage.tsx
  src/components/Header.tsx
  src/components/routes/ProjectCheckRoute.tsx
  src/recoil/atoms/header/headerState.ts
Labels: feat, design

#119 [#118] feat & design : LoadingPage 공통 컴포넌트 작성 및 적용
  src/assets/icons/calendar.gif
  src/components/LoadingPage.tsx
  src/components/routes/PrivateRoute.tsx
  src/components/routes/ProjectCheckRoute.tsx
  src/components/routes/PublicRoute.tsx
Labels: feat, design

#121 [#114] todo 모달 tag 생성/ 변경
  src/api/CreateCollection.tsx
  src/assets/icons/settingIconBlack.svg
  src/pages/ProjectListPage/CreateProjectBtn.tsx
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
  src/pages/ProjectPage/TodoModal/TagSelectLayout.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
  src/pages/ProjectPage/TodoModal/UpdateContent.tsx
Labels: feat

#125 [#124] feat : CommonSelectMemberlayout.tsx prop 수정
  src/components/layout/CommonSelectMemberLayout.tsx
Labels: feat

#129 [#127] design : 호버 색상 추가 및 탭 폰트 CSS 변경
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: design

#131 [#130] design : 칸반 모달 404 적용
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
Labels: design

#134 [#133] design & feat & fix : 팀멤버 모달 공통 레이아웃 활용하기 / 중복 내보내기 기능 추가 / atom 분리
  src/components/layout/CommonSelectMemberLayout.tsx
  src/components/layout/InputCommonLayout.tsx
  src/components/modal/ProjectMemberModal.tsx
  src/pages/ProjectPage/TodoModal/TagSelectLayout.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
  src/recoil/atoms/todo/singleTodoState.ts
Labels: fix, feat, design

#139 [#137] 태그 배경 색상 변경 기능
  src/pages/ProjectListPage/ProjectList.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/TodoModal/CustomOptions.tsx
  src/pages/ProjectPage/TodoModal/TagContainer.tsx
  src/pages/ProjectPage/TodoModal/TagSelectLayout.tsx
Labels: feat

#140 [#132] feat : kanbanModal 개선 및 기타 변경 사항
  package-lock.json
  package.json
  src/api/CreateCollection.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanStageBox.tsx
  src/pages/ProjectPage/KanbanModal/Stage.tsx
  src/pages/ProjectPage/KanbanModal/Todo.tsx
  src/pages/ProjectPage/Project.tsx
  src/recoil/atoms/todo/todoState.ts
Labels: fix, feat, refactor

#138 [#135] feat: 헤더 내 북마크 모달 구현
  src/components/modal/BookMarkModal.tsx
Labels: feat

#143 [#141] feat : 칸반모달 내 스테이지 및 투두 드래그 시 DB 업데이트
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanStageBox.tsx
  src/pages/ProjectPage/KanbanModal/Stage.tsx
  src/pages/ProjectPage/KanbanModal/Todo.tsx
Labels: feat

#148 [#147] feat & design : 칸반모달 스타일링 및 투두 이동시 stage_id 필드 추가
  src/api/CreateCollection.tsx
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanStageBox.tsx
  src/pages/ProjectPage/KanbanModal/Stage.tsx
Labels: feat, design

#150 [#146] refactor & feat : todoState를 recoil로 관리 / 투두 삭제 기능
  src/api/CreateCollection.tsx
  src/components/layout/CommonTextArea.tsx
  src/pages/ProjectPage/TodoModal/CustomOptions.tsx
  src/pages/ProjectPage/TodoModal/MarkdownEditor.tsx
  src/pages/ProjectPage/TodoModal/TagSelectLayout.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
  src/recoil/atoms/todo/singleTodoState.ts
Labels: feat, refactor

#152 [#145] design : 각 모달 탭 html 구조 변경
  src/components/layout/ProjectModalLayout.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/Stage.tsx
  src/pages/ProjectPage/Project.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
  src/utils/getBorderColorByBgColor.ts
Labels: design

#156 [#155] fix : a 태그 제거 및 투두 업데이트 작성자 및 실시간 오류 수정
  src/pages/ProjectListPage/ProjectCard.tsx
  src/pages/ProjectPage/TodoModal/UpdateContent.tsx
Labels: fix

#159 [#149] feat & design : 칸반모달, 스테이지 스타일링 및 스테이지 수정 삭제 기능 추가
  src/components/layout/CommonInputLayout.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanStageBox.tsx
  src/pages/ProjectPage/KanbanModal/Stage.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: feat, design

#163 [#158] design : 전체적인 css 문제 해결
  src/assets/images/deafultProjectImg.jpg
  src/assets/images/sidebarTestImg.png
  src/components/Header.tsx
  src/components/Sidebar.tsx
  src/components/layout/ProjectModalLayout.tsx
  src/components/modal/ProjectMemberModal.tsx
  src/components/modal/UserProfileModal.tsx
  src/pages/ProjectListPage/InvitationBtn.tsx
  src/pages/ProjectListPage/ProjectCard.tsx
  src/pages/ProjectListPage/ProjectList.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/Project.tsx
  src/pages/ProjectPage/TodoModal/MarkdownEditor.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: design

#165 [#160] feat & design : 칸반모달 내 투두 스타일링 및 투두 삭제기능 추가
  src/pages/ProjectPage/KanbanModal/KanbanStageBox.tsx
  src/pages/ProjectPage/KanbanModal/Stage.tsx
  src/pages/ProjectPage/KanbanModal/Todo.tsx
Labels: feat, design

#169 [#168] feat & design : 달력 내 모달 클릭 개선 및 튜토리얼 모달 추가
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/CalendarModal/CalendarTutorialModal.tsx
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
Labels: feat, design

#171 [#153] feat: 헤더 튜토리얼 모달 구현
  src/components/layout/ModalCommonLayout.tsx
  src/components/modal/TutorialModal.tsx
  src/components/modal/TutorialPagination.tsx
Labels: feat

#173 [#172] Refactor: 헤더 모달 개선
  src/components/Header.tsx
  src/components/layout/ModalCommonLayout.tsx
  src/components/modal/TutorialModal.tsx
Labels: fix, design

#174 [#170] feat & design : 칸반 복구 기능 추가
  src/components/Sidebar.tsx
  src/components/TrashBox.tsx
  src/components/layout/ProjectModalLayout.tsx
  src/pages/ProjectListPage/CreateProjectBtn.tsx
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/Stage.tsx
  src/pages/ProjectPage/Project.tsx
Labels: feat, design

#177 [#176] design: 캘린더 튜토리얼 모달 페이지네이션 적용 및 컨텐츠 추가
  src/components/layout/CommonPaginationLayout.tsx
  src/components/modal/TutorialModal.tsx
  src/pages/ProjectPage/CalendarModal/CalendarTutorialModal.tsx
Labels: design

#179 [#175] feat : user 하위컬렉션 onSnapshot 생성 및 userProfileModal 적용
  src/api/CreateCollection.tsx
  src/components/Header.tsx
  src/components/modal/UserProfileModal.tsx
  src/components/routes/ProjectCheckRoute.tsx
  src/pages/ProjectListPage/CreateProjectBtn.tsx
  src/recoil/atoms/userList/userListState.ts
Labels: feat

#180 [#164] 사이드바 최근 칸반 바로가기 기능
  src/components/routes/ProjectCheckRoute.tsx
  src/components/sidebar/RecentKanban.tsx
  src/components/sidebar/Sidebar.tsx
  src/pages/ProjectListPage/DeleteModal.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/Project.tsx
  src/recoil/atoms/sidebar/recentKanbanState.ts
  src/recoil/atoms/sidebar/todoLoaded.ts
Labels: feat

#183 refactor : 프로젝트 멤버 모달 recoilState로 변경
  src/components/layout/CommonSelectMemberLayout.tsx
  src/components/modal/ProjectMemberModal.tsx
  src/components/routes/ProjectCheckRoute.tsx
  src/pages/LoginPage/Login.tsx
Labels: feat, refactor

#184 [#175] fix : ProjectCheckRoute 오타 수정
  src/components/routes/ProjectCheckRoute.tsx
Labels: fix

#186 [#185] refactor : ProjectCheckRoute 리팩토링
  src/components/routes/ProjectCheckRoute.tsx
  src/pages/ProjectPage/Project.tsx
Labels: refactor

#191 [#189] design: CommonSelectMemberLayout container flex 속성값 추가
  src/components/layout/CommonSelectMemberLayout.tsx
  src/components/modal/ProjectMemberModal.tsx
Labels: design

#190 [#188] design: 튜토리얼 모달 윈도우 환경 디자인 수정
  src/components/modal/TutorialModal.tsx
  src/pages/ProjectPage/CalendarModal/CalendarTutorialModal.tsx
  src/pages/ProjectPage/KanbanModal/Stage.tsx
  src/pages/ProjectPage/KanbanModal/Todo.tsx
Labels: design

#196 [#194] feat : 프로젝트 리스트 페이지 로그아웃 버튼 추가
  src/assets/headerIcon/logout.svg
  src/components/Header.tsx
Labels: feat

#198 [#197] feat : 프로젝트 나가기 기능 추가
  src/components/modal/UserProfileModal.tsx
Labels: feat

#199 [#192] design : 헤더 아이콘 통일
  src/assets/headerIcon/bookmark.svg
  src/assets/headerIcon/log.svg
  src/assets/headerIcon/member.svg
  src/assets/headerIcon/tutorial.svg
  src/assets/icons/headerBellIcon.svg
  src/assets/icons/headerBookmarkIcon.svg
  src/assets/icons/headerInfoIcon.svg
  src/assets/icons/headerMemberIcon.svg
  src/components/Header.tsx
Labels: design

#202 [#200] fix : CommonSelectMemberLayout 유저 필터링 추가
  src/components/layout/CommonSelectMemberLayout.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
Labels: fix

#201 [#181] 전체적인 스타일링 수정
  src/components/Header.tsx
  src/components/TrashBox.tsx
  src/components/layout/CommonTextArea.tsx
  src/components/modal/ProjectMemberModal.tsx
  src/components/sidebar/RecentKanban.tsx
  src/components/sidebar/Sidebar.tsx
  src/pages/ProjectListPage/CreateProjectBtn.tsx
  src/pages/ProjectListPage/ProjectCard.tsx
  src/pages/ProjectListPage/ProjectIconContainer.tsx
  src/pages/ProjectListPage/ProjectList.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/TodoModal/MarkdownEditor.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: design

#204 [#203] fix : 칸반 생성 모달 종료일 - 1 수정
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
Labels: fix

#206 [#205] design : 모달 탭 및 쓰레기통 position : fixed 변경
  src/components/layout/ProjectModalLayout.tsx
  src/components/sidebar/Sidebar.tsx
  src/pages/ProjectPage/Project.tsx
Labels: design

#195 [#193] design: sweetalert2 라이브러리 적용
  package-lock.json
  package.json
  src/components/layout/ModalCommonLayout.tsx
  src/components/modal/BookMarkModal.tsx
  src/components/modal/ProjectMemberModal.tsx
  src/components/modal/UserProfileModal.tsx
  src/pages/ProjectListPage/CreateProjectBtn.tsx
  src/pages/ProjectListPage/ProjectIconContainer.tsx
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/Stage.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: design

#208 [#207] design : 모달 탭 박스 디자인 변경
  src/assets/ProjectModalTab.svg
  src/assets/images/projectModalTab.svg
  src/components/layout/ProjectModalLayout.tsx
  src/pages/ProjectPage/Project.tsx
Labels: design

#211 [#207] fix : 회원가입 시 유저 field 추가
  src/pages/LoginPage/Login.tsx
Labels: fix

#214 [#212] fix : 캘린더 드래그 및 드랍시 일정 변경 버그 수정
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
Labels: fix

#216 [#210] design : 로그인 페이지 디자인 변경
  src/pages/LoginPage/Login.tsx
Labels: design

#218 [#217] design : 프로젝트 리스트 페이지 폰트 및 grid 변경
  src/assets/logo/ProjectlistLogo.svg
  src/pages/ProjectListPage/InvitationBtn.tsx
  src/pages/ProjectListPage/ProjectList.tsx
Labels: design

#219 [#209] design: 칸반보드 프로그레스 바 백분율로 개선 / 초대링크 확장
  src/pages/ProjectListPage/InvitationBtn.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/Stage.tsx
Labels: design

#222 [#220] design : 각 모달 탭 스타일링 변경
  src/components/layout/ProjectModalLayout.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/Project.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: design

#224 design : 배경색에 따른 최근 칸반 텍스트 컬러 변경
  src/components/sidebar/RecentKanban.tsx
Labels: design

#225 [#221] design: 투두 모달 업데이트 UI 개선
  src/pages/ProjectPage/TodoModal/MarkdownEditor.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
  src/pages/ProjectPage/TodoModal/UpdateContent.tsx
Labels: design

#228 [#227] design : 프로젝트 리스트 / 프로젝트 페이지 전체적 디자인 수정
  src/assets/logo/headerLogo.svg
  src/components/Header.tsx
  src/components/layout/ProjectModalLayout.tsx
  src/components/routes/ProjectCheckRoute.tsx
  src/components/sidebar/RecentKanban.tsx
  src/components/sidebar/Sidebar.tsx
  src/index.tsx
  src/pages/ProjectListPage/InvitationBtn.tsx
  src/pages/ProjectListPage/ProjectList.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/Project.tsx
Labels: design

#230 [#229] design: 글로벌 스타일 및 기타 변경 사항
  src/assets/images/loginBackground.svg
  src/assets/logo/ProjectlistLogo.svg
  src/assets/logo/headerLogo.svg
  src/assets/logo/loginLogo.svg
  src/components/Header.tsx
  src/components/layout/ConfirmBtnLayout.tsx
  src/components/layout/ProjectModalLayout.tsx
  src/components/sidebar/Sidebar.tsx
  src/index.tsx
  src/pages/LoginPage/Login.tsx
  src/pages/ProjectListPage/InvitationBtn.tsx
  src/pages/ProjectListPage/ProjectList.tsx
  src/pages/ProjectPage/KanbanModal/KanbanStageBox.tsx
  src/pages/ProjectPage/Project.tsx
Labels: design

#232 [#231] design : 달력 모달 및 헤더 등 기타 스타일 수정
  package-lock.json
  package.json
  src/components/Header.tsx
  src/components/layout/ProjectModalLayout.tsx
  src/components/sidebar/Sidebar.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/Project.tsx
Labels: design

#235 [#234] design : 투두 페이지 태그 react-select 커스텀
  src/assets/icons/Cross.svg
  src/assets/icons/Pantone.svg
  src/components/layout/CommonInputLayout.tsx
  src/components/layout/CommonSelectMemberLayout.tsx
  src/components/sidebar/RecentKanban.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/TodoModal/CustomOptions.tsx
  src/pages/ProjectPage/TodoModal/TagContainer.tsx
  src/pages/ProjectPage/TodoModal/TagSelectLayout.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: design

#239 [#233] design : 쓰레기통 모달 및 기타 스타일링 수정
  src/assets/icons/Delete.svg
  src/assets/icons/update.svg
  src/components/layout/ProjectModalLayout.tsx
  src/components/sidebar/RecentKanban.tsx
  src/components/sidebar/Sidebar.tsx
  src/index.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/CalendarModal/TrashModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/Project.tsx
Labels: design

#240 [#236] design : react-select 공통 레이아웃 수정
  src/components/DatePicker.tsx
  src/components/layout/CommonSelectMemberLayout.tsx
  src/components/layout/CommonTextArea.tsx
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
  src/pages/ProjectPage/TodoModal/CustomOptions.tsx
  src/pages/ProjectPage/TodoModal/TagContainer.tsx
  src/pages/ProjectPage/TodoModal/TagSelectLayout.tsx
Labels: design

#242 [#241] design : 칸반모달 디자인 수정사항 반영
  src/assets/icons/dots.svg
  src/assets/icons/plus.svg
  src/assets/images/loginBackground.jpg
  src/assets/images/loginBackground.svg
  src/components/layout/CommonInputLayout.tsx
  src/pages/LoginPage/Login.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanMoreModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanStageBox.tsx
  src/pages/ProjectPage/KanbanModal/Stage.tsx
  src/pages/ProjectPage/KanbanModal/Todo.tsx
Labels: design

#244 [#238] 사이드바 레이아웃 UI 개선
  src/components/sidebar/RecentKanban.tsx
  src/components/sidebar/Sidebar.tsx
Labels: design

#248 [#247] fix & design : 투두 업데이트 문제 해결 / 투두 업데이트 디자인 수정
  src/api/CreateCollection.tsx
  src/components/layout/ConfirmBtnLayout.tsx
  src/pages/ProjectPage/TodoModal/MarkdownEditor.tsx
  src/pages/ProjectPage/TodoModal/UpdateContent.tsx
Labels: fix, design

#252 [#250] feat : userListData를 이용한 최신 유저 데이터 변경
  src/components/layout/CommonSelectMemberLayout.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/Todo.tsx
  src/pages/ProjectPage/KanbanModal/UserSelectLayout.tsx
Labels: feat

#254 [#253] fix : 폰트 임포트 시 파일형식 추가
  src/index.tsx
Labels: fix

#256 [#255] chore : 불필요한 CSS 제거
  public/index.html
Labels: chore

#258 [#257] design : 칸반 복구 모달 스타일 수정
  src/components/layout/ProjectModalLayout.tsx
  src/pages/ProjectPage/CalendarModal/TrashModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
Labels: design

#261 [#260] design : 완료 스테이지의 경우 체크표시 추가
  src/assets/icons/Check.svg
  src/pages/ProjectPage/KanbanModal/Stage.tsx
Labels: design

#259 [#251] design: 사이드바 추가 개선 / 헤더 튜토리얼 div hoverColor 속성 추가
  src/components/Header.tsx
  src/components/sidebar/RecentKanban.tsx
  src/components/sidebar/Sidebar.tsx
Labels: design

#267 [#263] 최근칸반 뒤로가기 문제 해결
  src/components/sidebar/RecentKanban.tsx
  src/pages/ProjectPage/Project.tsx
Labels: fix

#269 [#263] feat : 칸반 및 투두 삭제시 딜레이 추가
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
  src/utils/asyncDelay.ts
Labels: feat

#265 [#262] refactor: 튜토리얼 컨텐츠 추가
  src/components/modal/TutorialModal.tsx
  src/components/sidebar/RecentKanban.tsx
  src/components/sidebar/Sidebar.tsx
Labels: design, refactor

#268 [#266] refactor: Sweetalert2 버튼 색상 변경
  src/components/modal/TutorialModal.tsx
  src/pages/ProjectListPage/CreateProjectBtn.tsx
  src/pages/ProjectListPage/ProjectCardMoreModal.tsx
Labels: refactor

#271 [#263] feat : 최근칸반 선택시 투두 404 해결
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: feat

#274 [#273] design & docs : 세부 디자인 수정 / 안 쓰는 파일 제거
  src/assets/icons/linkIcon.svg
  src/assets/icons/paint.svg
  src/assets/icons/pencilIcon.svg
  src/assets/icons/pictureIcon.svg
  src/assets/icons/reloadIcon.svg
  src/assets/icons/settingIcon.svg
  src/assets/icons/settingIconBlack.svg
  src/assets/images/deafultProjectImg.jpg
  src/assets/images/defaultProjectImg2.jpg
  src/components/layout/CommonSelectMemberLayout.tsx
  src/components/layout/ProjectModalLayout.tsx
  src/components/sidebar/Sidebar.tsx
  src/pages/ProjectListPage/DeleteModal.tsx
  src/pages/ProjectListPage/InvitationBtn.tsx
  src/pages/ProjectListPage/ProjectCard.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/UserSelectLayout.tsx
  src/pages/ProjectPage/Project.tsx
  src/pages/ProjectPage/TodoModal/MarkdownEditor.tsx
  src/pages/ProjectPage/TodoModal/TagSelectLayout.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
  src/pages/ProjectPage/TodoModal/TodoUpdateMoreModal.tsx
  src/pages/ProjectPage/TodoModal/UpdateContent.tsx
Labels: docs, design

#276 [#263] design : 여러 디자인 항목 수정
  src/assets/icons/Cross.svg
  src/assets/icons/update.svg
  src/components/sidebar/RecentKanban.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/CalendarModal/TrashModal.tsx
  src/pages/ProjectPage/KanbanModal/Stage.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: design

#278 [#277] refactor: 튜토리얼 구조 개선
  src/components/Header.tsx
  src/components/layout/CommonPaginationLayout.tsx
  src/components/modal/TutorialModal.tsx
Labels: design, refactor

#279 [#270] feat: 프로젝트 리스트 페이지 제목 길이 제한 / 초대링크 localhost 제거
  src/pages/ProjectListPage/InvitationBtn.tsx
  src/pages/ProjectListPage/ProjectCard.tsx
  src/utils/handleCopyClipBoard.tsx
Labels: feat

#283 [#281] design : 1차 개발 마무리
  public/index.html
  src/assets/icons/defaultProfile.png
  src/components/DatePicker.tsx
  src/components/Header.tsx
  src/components/layout/ConfirmBtnLayout.tsx
  src/components/layout/ProjectModalLayout.tsx
  src/components/modal/BookMarkModal.tsx
  src/components/modal/ProjectMemberModal.tsx
  src/components/modal/TutorialModal.tsx
  src/components/modal/UserProfileModal.tsx
  src/components/routes/ProjectCheckRoute.tsx
  src/components/sidebar/RecentKanban.tsx
  src/components/sidebar/Sidebar.tsx
  src/index.tsx
  src/pages/ProjectListPage/CreateProjectBtn.tsx
  src/pages/ProjectListPage/ProjectCard.tsx
  src/pages/ProjectListPage/ProjectCardMoreModal.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
  src/pages/ProjectPage/CalendarModal/TrashModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/KanbanModal/KanbanMoreModal.tsx
  src/pages/ProjectPage/KanbanModal/Stage.tsx
  src/pages/ProjectPage/KanbanModal/Todo.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
  src/pages/ProjectPage/TodoModal/TodoMoreModal.tsx
  src/pages/ProjectPage/TodoModal/TodoUpdateMoreModal.tsx
  src/pages/ProjectPage/TodoModal/UpdateContent.tsx
Labels: design

#285 진짜찐막
  src/components/layout/CommonSelectMemberLayout.tsx
  src/components/modal/ProjectMemberModal.tsx
  src/components/sidebar/RecentKanban.tsx
  src/pages/ProjectPage/KanbanModal/UserSelectLayout.tsx
Labels: fix

#286 찐찐찐찐막
  src/components/layout/CommonSelectMemberLayout.tsx
Labels: fix

#287 fix : 기본 프로필 이미지 버그 수정
  src/pages/ProjectPage/KanbanModal/Todo.tsx
  src/pages/ProjectPage/TodoModal/UpdateContent.tsx
Labels: fix

#288 design : 파비콘 추가
  public/favicon.svg
  public/index.html
Labels: design

#289 design : 놓친 스타일 수정 및 이메일 검증 수정
  src/assets/icons/Cross.svg
  src/assets/icons/CrossNoFill.svg
  src/components/modal/ProjectMemberModal.tsx
  src/components/sidebar/RecentKanban.tsx
  src/pages/ProjectPage/KanbanModal/CustomUserOptions.tsx
  src/pages/ProjectPage/KanbanModal/Todo.tsx
  src/pages/ProjectPage/KanbanModal/UserSelectLayout.tsx
Labels: design

#291 [#290] feat : textarea shift+enter 누를 시 줄바꿈
  src/components/layout/CommonTextArea.tsx
  src/components/modal/UserProfileModal.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: feat

#293 [#292] design : 칸반 및 투두 모달 제목 input 수정
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: design

#295 [#294] design : textarea max-height 추가
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: design

#297 docs : readme 작성
  README.md
Labels: docs

#298 docs : readme.md gif 추가
  README.md
Labels: docs
