Repository wowba/Calit, pull requests merged in 2023-10, with the labels that each got.

#4 Feat : RecoilRoot 및 BrowserRouter 추가
  src/index.tsx
Labels: feat

#6 [#5] Feat : firebaseSDK 추가
  package-lock.json
  package.json
  src/firebaseSDK.ts
Labels: feat

#8 [#7] design : css reset 용 GlobalStyle 추가
  src/index.tsx
Labels: design

#10 [#9] Chore : 폴더 구조 추가
  src/api/.gitkeep
  src/assets/.gitkeep
  src/components/.gitkeep
  src/pages/.gitkeep
  src/recoil/atoms/.gitkeep
  src/recoil/selectors/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
Labels: chore

#12 [#11] Feat : 프로젝트 라우터 구조 작성 및 기본 컴포넌트 추가
  src/App.tsx
  src/components/Header.tsx
  src/components/Sidebar.tsx
  src/components/routes/PrivateRoute.tsx
  src/components/routes/ProjectCheckRoute.tsx
  src/components/routes/PublicRoute.tsx
  src/pages/LoginPage/Login.tsx
  src/pages/ProjectListPage/ProjectList.tsx
  src/pages/ProjectPage/Project.tsx
Labels: feat

#14 [#13]feat : project.tsx 테스트 코드 작성
  src/pages/ProjectPage/Project.tsx
Labels: feat

#17 [#15] Feat : query를 이용한 project.tsx 예시 코드 작성
  src/pages/ProjectPage/Project.tsx
Labels: feat

#19 [#18] Chore : recoil-persist 설치
  package-lock.json
  package.json
Labels: chore

#23 [#20] Feat: 로그인 기능 및 public, private router 추가
  firestore.rules
  src/components/routes/PrivateRoute.tsx
  src/components/routes/PublicRoute.tsx
  src/pages/LoginPage/Login.tsx
  src/recoil/atoms/login/loginState.ts
  src/recoil/atoms/login/userState.ts
  storage.rules
Labels: feat

#25 [#22] Feat : 초대 링크로 입장 버튼 기능 구현
  src/components/layout/ConfirmBtnLayout.tsx
  src/pages/ProjectListPage/InvitationBtn.tsx
  src/pages/ProjectListPage/ProjectList.tsx
Labels: feat

#32 [#29] feat : 로그인 유저 정보 실시간으로 받아오기
  src/components/routes/PrivateRoute.tsx
  src/components/routes/PublicRoute.tsx
  src/pages/LoginPage/Login.tsx
  src/recoil/atoms/login/loginState.ts
  src/recoil/atoms/login/userDataState.ts
Labels: feat

#34 [#33] Design : Sidebar.tsx 초안 작성
  src/assets/icons/trashIcon.svg
  src/assets/images/sidebarTestImg.png
  src/components/Sidebar.tsx
  src/components/routes/ProjectCheckRoute.tsx
Labels: design

#36 [#26] Feat : 리스트 페이지 project card 제작 및 읽어오기
  src/assets/Rectangle.svg
  src/pages/ProjectListPage/ProjectCard.tsx
  src/pages/ProjectListPage/ProjectList.tsx
Labels: feat, design

#42 [#35] design : Sidebar.tsx, Project.tsx, ProjectCheckRoute.tsx 스타일링 및 기타...
  src/assets/ProjectModalTab.svg
  src/components/Sidebar.tsx
  src/components/layout/ProjectModalLayout.tsx
  src/components/routes/ProjectCheckRoute.tsx
  src/index.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/Project.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: design

#39 [#37] feat: 프로젝트 생성 로직 구현
  src/api/CreateCollection.tsx
  src/assets/icons/icon_plus_circle.svg
  src/assets/images/Rectangle.svg
  src/pages/ProjectListPage/CreateProjectBtn.tsx
  src/pages/ProjectListPage/ProjectCard.tsx
  src/pages/ProjectListPage/ProjectList.tsx
Labels: feat, design

#45 [#43] Feat : 프로젝트 페이지 모달 디자인 및 클릭시 팝업 구현
  src/components/layout/ProjectModalLayout.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/Project.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: feat, design

#47 [#46] fix : 프로젝트 공통 모달 배경색 지정 위치 변경
  src/components/layout/ProjectModalLayout.tsx
Labels: fix

#49 [#48] refactor : ProjectModalContent 스타일 컴포넌트 제거
  src/components/layout/ProjectModalLayout.tsx
  src/pages/ProjectPage/KanbanModal/KanbanModal.tsx
  src/pages/ProjectPage/Project.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: refactor

#51 #31 feat: 헤더 모달 컴포넌트 구현
  src/assets/icons/headerBellIcon.svg
  src/assets/icons/headerBookmarkIcon.svg
  src/assets/icons/headerInfoIcon.svg
  src/assets/icons/headerMemberIcon.svg
  src/assets/icons/headerProfileSampleIcon.svg
  src/components/Header.tsx
  src/components/layout/ModalCommonLayout.tsx
  src/components/modal/BookMarkModal.tsx
  src/components/modal/LogModal.tsx
  src/components/modal/ProjectMemberModal.tsx
  src/components/modal/TutorialModal.tsx
  src/components/modal/UserProfileModal.tsx
Labels: feat

#56 [#50] design : 달력 모달 스타일링 및 컴포넌트 분리
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/Project.tsx
Labels: feat, design

#54 [#53] design : 헤더 내 각 모달 구조 변경
  src/components/Header.tsx
  src/components/layout/ModalCommonLayout.tsx
  src/components/modal/BookMarkModal.tsx
  src/components/modal/LogModal.tsx
  src/components/modal/ProjectMemberModal.tsx
  src/components/modal/TutorialModal.tsx
  src/components/modal/UserProfileModal.tsx
Labels: feat, design

#60 [#59] feat : ProjectCheckRoute 기능 추가
  src/components/Sidebar.tsx
  src/components/routes/ProjectCheckRoute.tsx
  src/recoil/atoms/project/projectState.ts
Labels: feat

#71 [#66] feat : ProjectCheckRoute 초대 링크 기능 추가
  src/components/routes/ProjectCheckRoute.tsx
Labels: feat

#73 [#72] feat : 드래그로 칸반 생성 및 칸반 컬렉션 실시간 연동 추가
  src/api/CreateCollection.tsx
  src/components/routes/ProjectCheckRoute.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
  src/recoil/atoms/kanban/kanbanState.ts
  src/utils/yearMonthDayFormat.ts
  tsconfig.json
Labels: feat

#75 [#74] design & feat : 공통 Text Input 컴포넌트 생성 및 칸반 생성 모달에 반영
  src/components/layout/CommonInputLayout.tsx
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
Labels: feat, design

#77 [#76] chore & feat & design : react-datepicker 관련 라이브러리 설치 및 DatePicker 공통 컴포넌트 추가
  package-lock.json
  package.json
  src/components/DatePicker.tsx
  src/components/layout/CommonInputLayout.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
Labels: feat, design, chore

#79 [#78] feat & design : CommonSelectMemberLayout 공통 컴포넌트 작성 및 1차 스타일 적용
  package-lock.json
  package.json
  src/components/DatePicker.tsx
  src/components/layout/CommonSelectMemberLayout.tsx
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
Labels: feat, design, chore

#81 [#80] fix : DatePicker @ts-ignore 추가
  src/components/DatePicker.tsx
Labels: fix

#83 [#82] feat : 달력 칸반 클릭시 칸반 모달 팝업
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/Project.tsx
Labels: feat

#86 [#85] feat : 칸반 색상 할당 / 드래그, 리사이즈 이벤트 추가
  src/api/CreateCollection.tsx
  src/pages/ProjectListPage/CreateProjectBtn.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/CalendarModal/CreateKanbanModal.tsx
  src/utils/getBorderColorByBgColor.ts
  src/utils/getTextColorByBgColor.ts
Labels: feat

#84 [#70] feat & design : todo 모달 firebase 연동 / todo 모달 레이아웃
  src/components/DatePicker.tsx
  src/components/layout/CommonInputLayout.tsx
  src/components/layout/CommonTextArea.tsx
  src/pages/ProjectListPage/ProjectList.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: feat, design

#88 [#87] feat & design : 유저 프로필 모달 스타일링 / 유저정보 수정 / 로그아웃 추가
  src/assets/icons/headerProfileSampleIcon.svg
  src/components/Header.tsx
  src/components/layout/ModalCommonLayout.tsx
  src/components/modal/UserProfileModal.tsx
  src/pages/ProjectListPage/ProjectIconContainer.tsx
Labels: feat, design

#92 [#90] feat & design : 업데이트
  src/pages/ProjectPage/TodoModal/MarkdownEditor.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
  src/pages/ProjectPage/TodoModal/UpdateContent.tsx
  src/recoil/atoms/todo/todoState.ts
Labels: feat, design

#95 [#93] feat : 업데이트 컴포넌트 변경 모달 추가 (변경취소 / 삭제)
  src/assets/icons/pencilIcon.svg
  src/assets/icons/reloadIcon.svg
  src/assets/images/Arrow.svg
  src/components/layout/CommonSettingModal.tsx
  src/pages/ProjectListPage/ProjectIconContainer.tsx
  src/pages/ProjectPage/TodoModal/MarkdownEditor.tsx
  src/pages/ProjectPage/TodoModal/UpdateContent.tsx
Labels: feat

#97 feat : todo 담당자 추가/수정/삭제
  src/components/layout/CommonSelectMemberLayout.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: feat

#99 design: Header CSS 변경
  src/components/Header.tsx
  src/components/Sidebar.tsx
  src/components/layout/ProjectModalLayout.tsx
Labels: design

#102 [#94] design : 투두 페이지 레이아웃 수정 및 toolbar 보여짐 여부 설정
  src/components/layout/CommonTextArea.tsx
  src/pages/ProjectPage/TodoModal/MarkdownEditor.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
  src/pages/ProjectPage/TodoModal/UpdateContent.tsx
Labels: design

#105 design : 모달 탭 호버시 포인터 및 색상 변경
  src/components/layout/ProjectModalLayout.tsx
  src/pages/ProjectPage/CalendarModal/CalendarModal.tsx
  src/pages/ProjectPage/TodoModal/TodoModal.tsx
Labels: design

#107 [#106] design : GlobalStyle 폰트 추가 및 themeProvider 생성
  src/index.tsx
Labels: design
